//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Image.h
//  @ Date : 6/15/2012
//  @ Author : 
//
//


#if !defined(_IMAGE_H)
#define _IMAGE_H

#include "GraphicMain.h"
#include "Factory.h"
#include "../core/Resource.h"

namespace gata {
	namespace graphic {
//===================================================================================
using namespace gata::core;

class Image : public Resource
{
public:
	Image(): Resource(), m_width(0), m_height(0) { }
	virtual ~Image() { }

	int width() { return m_width; }
	int height() { return m_height; }

	static Image* create()
	{
		return GraphicMain::getFactory()->createImage();
	}

protected:
	int m_width;
	int m_height;
};
//===================================================================================
	}
}

#endif  //_IMAGE_H
