//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Transform.h
//  @ Date : 6/15/2012
//  @ Author : 
//
//


#if !defined(_TRANSFORM_H)
#define _TRANSFORM_H

namespace gata {
	namespace graphic {
//===================================================================================
enum TransformType
{
	ROTATE_90 = 0,
	ROTATE_180 = 1,
	ROTATE_270 = 2,
	FLIP_X = 3,
	FLIP_Y = 4
};

#define MAX_TRANSFORM_COUNT 32

class Transform
{
public:
	Transform() : m_count(0) { }

	TransformType* getList() { return m_pList; }

	int getCount() { return m_count; }

	void append(TransformType e);

	bool isChangeOri();
			
	static Transform concat(Transform* p1, Transform* p2);

private:
	TransformType m_pList[MAX_TRANSFORM_COUNT];
	int m_count;
};
//===================================================================================
	}
}

#endif  //_TRANSFORM_H
