C:\Kata\Projects\XepBiMau\res\ball.gif
C:\Kata\Projects\XepBiMau\res\num.gif
C:\Kata\Projects\XepBiMau\res\undo.gif
C:\Kata\Projects\XepBiMau\res\home.gif
C:\Kata\Projects\XepBiMau\res\font_bm_large.gif
C:\Kata\Projects\XepBiMau\res\font_bm_medium.gif
C:\Kata\Projects\XepBiMau\res\music.mid
C:\Kata\Projects\XepBiMau\res\move.mid
C:\Kata\Projects\XepBiMau\res\score.mid
